Configuration
andersonlebon/todo-list pull request #1
Opened 2021-07-20 19:49 UTC by andersonlebon

### Here are what I managed to do :

- [ ] Set up a new project that is based on the webpack.
- [ ] Create an index.html file and write your HTML markup here.
- [ ]  Create an empty To-Do List placeholder(`ul`).
- [ ] Create an index.js file and set an array of some simple to-do tasks (array of objects). Each task object contains three keys:
- description [string].
- completed [bool].
- index: [number].
- [ ] Write a function to iterate over the tasks array and populate an HTML list item element for each task.
- [ ] On page load renders the dynamically created list of tasks in the dedicated placeholder. T
- [ ] Create a style.css and set rules for the To-Do List. CSS must be loaded by Webpack Style/CSS Loader.

2021-07-20 23:10 UTC, mricanho requested changes
Hi @andersonlebon, 

Good job so far! 🔥🔥 Your gitflow, commit messages and almost all your README file it's ok, your JS code it's excellent nothing more to add there.

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] **Remember that all the linters must pass in order to approve your project, this is a hard requirement**

- [ ] Remember that you need to style your app to match the target style, please work on that (Add a title, "Add to your list" input, icons, etc.)

Your style:

![image](https://user-images.githubusercontent.com/60631456/126406433-322a8a19-b773-492c-a417-376726b61cd7.png)

target style:

![image](https://user-images.githubusercontent.com/60631456/126406464-6cea79ee-1f21-432c-8638-02aaf1bc7d7d.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![believe in change](https://user-images.githubusercontent.com/60631456/126406490-6b077473-b0e8-45d6-ba84-611dcba72c15.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-20 23:10 UTC, mricanho commented on README.md
> +  > `npx eslint .`
- [ ] Add the command `npm run build` or the necessary command to run your app in the live server

2021-07-21 11:11 UTC, ZawadiSumba66 requested changes
#### Hi @andersonlebon 👋 , 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there is bug that came up when implementing one of the changes

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-21 11:11 UTC, ZawadiSumba66 commented on package.json
> +  },
- [ ] When I try to start the server, with npm start, the operation terminates and the server does not open. This is because the start and the build commands are incorrectly set up. Kindly check out this [link](https://webpack.js.org/guides/development/#using-webpack-dev-server) on how to set up. There is also the `devServer` command that needs to be placed in the `webpack.config.js`

2021-07-21 11:11 UTC, ZawadiSumba66 commented on src/index.html
> +            <i class="fa fa-plus-circle" aria-hidden="true"></i>
- [ ] In regards to the style of your to-do list there should be a  `clear completed task ` button at the bottom of the list.
see screensot
![image](https://user-images.githubusercontent.com/68167810/126479540-e36abdb9-8ecd-4f54-8404-5bc8b215dd92.png)

2021-07-21 11:35 UTC, andersonlebon commented on src/index.html
> +            <i class="fa fa-plus-circle" aria-hidden="true"></i>
@ZawadiSumba66 hello there, I have changed according to what you said, may you please check if everything is okay before I request my last review? I just have one left

2021-07-21 12:44 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @andersonlebon. 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-22 00:29 UTC, andersonlebon commented on .github/workflows/linters.yml
> +    name: ESLint
okey

2021-07-22 00:30 UTC, andersonlebon commented
okey

2021-07-22 10:49 UTC, merged